apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera-ns-0-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.165
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: agent
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app.kubernetes.io/instance: mariadb-galera-ns
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-galera-ns-0
  publishNotReadyAddresses: true
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera-ns-1-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.166
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: agent
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app.kubernetes.io/instance: mariadb-galera-ns
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-galera-ns-1
  publishNotReadyAddresses: true
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera-ns-2-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.167
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: agent
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app.kubernetes.io/instance: mariadb-galera-ns
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-galera-ns-2
  publishNotReadyAddresses: true
  type: LoadBalancer