name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  detect-noop:
    runs-on: ubuntu-latest
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect no-op changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          paths_ignore: '["**.md"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
          concurrent_skipping: false

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: make build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cluster
        run: |
          make cluster
          make install

      - name: MariaDB test host
        run: sudo make mdb-add-test-host

      - name: Test
        run: make test

  check-diff:
    name: Check diff
    runs-on: ubuntu-latest
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate
        run: make generate

      - name: Check diff
        uses: ./.github/actions/check-diff
        with:
          message: Generated artifacts are not up to date. Run 'make generate' and commit the changes.
